version: "3.7"

services:
  frontend:
    container_name: checkout-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_API_URL=http://localhost:3000

  backend:
    container_name: checkout-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/app"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ENVIRONMENT=local
